Repository PleasPlan/OMO-API, pull requests merged in 2024-05, with the labels that each got.

#1 [BE] cors 허용 메서드에 PUT 추가
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/config/WebConfig.java
Labels: bug

#5 [BE] 게시판 좋아요 요청 시 boardId를 @PathVariable을 통해 받아오도록 수정
  src/main/java/com/OmObe/OmO/Board/controller/BoardController.java
Labels: enhancement

#6 [BE] CorsConfiguration 허용 헤더 설정
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
Labels: enhancement

#7 Be feat/board user liked tf
  src/main/java/com/OmObe/OmO/Board/controller/BoardController.java
  src/main/java/com/OmObe/OmO/Board/dto/BoardDto.java
  src/main/java/com/OmObe/OmO/Board/mapper/BoardMapper.java
  src/main/java/com/OmObe/OmO/Board/service/BoardService.java
  src/main/java/com/OmObe/OmO/Liked/repository/LikedRepository.java
  src/main/java/com/OmObe/OmO/auth/jwt/TokenDecryption.java
Labels: enhancement

#8 [BE] 관리자 닉네임 설정
  src/main/java/com/OmObe/OmO/auth/oauth/service/OAuth2MemberService.java
Labels: enhancement

#9 Be feat/my page category
  src/main/java/com/OmObe/OmO/Board/dto/BoardDto.java
  src/main/java/com/OmObe/OmO/MyPage/controller/MyPageController.java
  src/main/java/com/OmObe/OmO/MyPage/service/MyPageService.java
  src/main/java/com/OmObe/OmO/MyPage/utility/pageUtility.java
Labels: enhancement

#10 [BE] 인증 처리 코드 구조 정리
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/oauth/service/OAuth2MemberService.java
  src/main/java/com/OmObe/OmO/auth/userdetails/MemberDetailsService.java
Labels: documentation

#11 feat: comment 생성 및 최근 변동 시간 출력 기능 추가
  src/main/java/com/OmObe/OmO/Comment/dto/CommentDto.java
  src/main/java/com/OmObe/OmO/Comment/mapper/CommentMapper.java
Labels: enhancement

#12 fix: 좋아요가 false일 시 500에러가 나오는 버그를 수정함.
  src/main/java/com/OmObe/OmO/Board/mapper/BoardMapper.java
Labels: bug

#13 Revert "feat: category별로 내가 쓴 글 분류해서 볼 수 있는 기능 추가"
  src/main/java/com/OmObe/OmO/MyPage/controller/MyPageController.java
  src/main/java/com/OmObe/OmO/MyPage/service/MyPageService.java
Labels: enhancement

#14 [BE] member-board 엔티티 cascade 설정
  src/main/java/com/OmObe/OmO/member/entity/Member.java
Labels: enhancement
